### ISSUE TITLE
Broken key interpretation when NAME field has a space character

### ISSUE THREAD

**Issue by bruindustin** [scito/extract_otp_secret_keys#1]
The bug title pretty much explains it all. I played with this tool and it largely worked exactly as one would hope. All inputs successfully generated an output and a QR code, however, certain codes would not scan by GAuth. Upon studying the various permutations I realized it is the presence of space characters in the NAME field that seems to break the system. I replaced those on the upstream device with underscore characters and re-exported. Everything worked great that time.

I'm going to guess there's an improper chunk detector that's getting tricked by whitespace and thus breaking the secret.

**Comment by scito** [comment]
I could not reproduce the problem.
Nevertheless, I've made a change. I quote the otp.name for printing the QR code.
@bruindustin Can you check if the changed version works with spaces? If no, please reopen the issue.

**Comment by bruindustin** [comment]
Confirmed - that has fixed the issue on my test cases!

**Comment by scito** [comment]
@bruindustin Thanks for checking!
