### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message When trying to decode multiple accounts.

### ISSUE THREAD

**Issue by MachineGalaxy** [scito/extract_otp_secret_keys#15]
When trying to decode multiple accounts, I get the error: 
```
Traceback (most recent call last):
  File "extract_otp_secret_keys.py", line 217, in <module>
    sys_main()
  File "extract_otp_secret_keys.py", line 57, in sys_main
    main(sys.argv[1:])
  File "extract_otp_secret_keys.py", line 66, in main
    otps = extract_otps(args)
  File "extract_otp_secret_keys.py", line 98, in extract_otps
    payload = get_payload_from_line(line, i, args)
  File "extract_otp_secret_keys.py", line 138, in get_payload_from_line
    payload.ParseFromString(data)
google.protobuf.message.DecodeError: Error parsing message
```
I tried only exporting a single account, and that worked fine. However, anything more and the problem fails regardless if they are in a single QR code or multiple.

Windows 10
Python 3.7.3
protobuf-4.21.5
qrcode-7.3.1

**Comment by scito** [comment]
It seems to work for. I cannot reproduce it.

The following command works for me.

`python extract_otp_secret_keys.py example_export.txt`

Can you try it?
What is the result of it?

**Comment by MachineGalaxy** [comment]
So the example_export.txt works fine. 
My guess is that its something to do with the export I got. 
I also tried this on a VM with a fresh install of Windows and got the same error.

**Comment by scito** [comment]
I've enabled base64 decode validation on master. This change excludes base64 decode problems. Can you try with the latest master?

The problems seems to be in protobuf.

Can you try with other exports?

I need to reproduce your problem on my computer, otherwise I cannot analyze the problem.
Can you send me steps for reproduction of the problem?
(BTW: Do not send the original file with your secrets.)

**Comment by scito** [comment]
Thanks for your test data!

I could reproduce and fix the problem.

Can you test if it works?

**Comment by MachineGalaxy** [comment]
Yup, that's fixed the issue.
Thanks
