### ISSUE TITLE
Pass arguments as strings

### ISSUE THREAD

**Issue by Levminer** [scito/extract_otp_secret_keys#4]
Hi!

I'm using this file in my project (https://github.com/Levminer/authme) to convert google authenticator links to 2FA codes.

I want to pass the strings as arguments seperated by spaces.

Example
`python extract_otp_secret_keys.py otpauth-migration://offline?data=123... otpauth-migration://offline?data=123...`

Can you help me with that? 
Thank you!

**Comment by scito** [comment]
Hi

I think you have to change in extract_otp_secret_keys.py
* line 53ff for accepting strings and
* line 84 for adapting the loop for strings.

Note: The script should work with stdin, see line 57. So you could use pipes.

**Comment by Levminer** [comment]
Thank you I'm very bad at pyhton, but somehow made it work!
